// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	ID        string  `json:"id"`
	Username  string  `json:"username"`
	Email     string  `json:"email"`
	Firstname *string `json:"firstname"`
	Lastname  *string `json:"lastname"`
	Gender    *string `json:"gender"`
	Phone     string  `json:"phone"`
	Password  string  `json:"password"`
}
