// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewQaAnswerLater struct {
	ID         string `json:"id"`
	QuestionID int    `json:"questionId"`
}

type NewQaHide struct {
	ID         string `json:"id"`
	HideByUser int    `json:"hideByUser"`
	QuestionID int    `json:"questionId"`
}

type NewQaReport struct {
	ID          string `json:"id"`
	Reason      string `json:"reason"`
	Description string `json:"description"`
	QuestionID  int    `json:"questionId"`
}

type NewUser struct {
	ID        string  `json:"id"`
	Username  string  `json:"username"`
	Email     string  `json:"email"`
	Firstname *string `json:"firstname"`
	Lastname  *string `json:"lastname"`
	Gender    *string `json:"gender"`
	Phone     string  `json:"phone"`
	Password  string  `json:"password"`
}
